added a function hangman_loop
itsabhianant/hangman pull request #1
Opened 2021-04-12 09:52 UTC by cpyberry

Hello, I am cpyberry.
If you happen to have a free moment, I'd be very glad if you could give me your opinion.

## Contents

* we can choose whether to play the game again

2021-04-12 09:55 UTC, cpyberry commented
It has been a long time since we last contacted each other.
This play is fun.

2021-04-12 16:41 UTC, itsabhianant commented
Hi @cpyberry ,

It's good to see you again and thanks for showing the will of enhancing the project. I really appreciate it... There are some changes that are needed to be done so that the program becomes cooler. Please see to it.

Best, 
Abhishek

2021-04-12 17:09 UTC, itsabhianant requested changes
There is a problem in this code. The message regarding how to quit is not shown and the game continues on its own.
Here is how you can change it:

1. Change ```while inputed_char != end_char:``` to ```while True:``` -> this makes us use the while loop until we want to ```break``` it
2. Get ```inputed_char = input(content)``` 
3. Now get an if statement that has the condition ```inputed_char != end_char:```
4. Call ```hangman()```
5. Get an else statement with no condition and then ```break``` the while loop 

***At last let me tell you how your code should look like:***

```py
while True:
        inputed_char = input(content)
        if inputed_char != end_char:
            hangman()
        else:
            break
```

***It will also be a good idea if you tell the user to press any key (except 'q' ) to continue playing the game.***

**Once you are done making these changes please do rebase and squash your commits .**

2021-04-12 17:09 UTC, noturshek commented on hangman.py
> +        inputed_char = input(content)
This line should be at line no. 70. Also after making these changes the game asks to quit only once that is if you don't wish to quit it the first time it will never bother to ask you again if you want to continue or quit and you will have to press ```Ctrl + c``` to quit which I don't wish to because it shows information about the program to the user.

Make a change in such a way that the game asks the user to continue or quit every time the game ends independent of the result.

2021-04-13 12:36 UTC, itsabhianant commented
Hi @cpyberry,

This is to inform you that I am closing your PR as it's been a day since you responded and I have made some major changes in the program. But don't be angry/sad because if you go down in the program you will see a TODO list. If you want you can work on that. Also, I raised an issue in my [rock-paper-scissors](https://github.com/itsabhianant/rock_paper_scissors) repository. If you want you can work on this [issue](https://github.com/itsabhianant/rock_paper_scissors/issues).

Best,
Abhishek

2021-04-13 12:36 UTC, closed without merging

2021-04-13 12:42 UTC, cpyberry commented
I just missed the timing!
I just rebase and push

2021-04-13 13:01 UTC, itsabhianant commented
Oh shoot... I feel so bad. Don't worry I still have to do the enhancement of the program. I have listed below in hangman.py in the todo list. It will be great if you can make those changes. Also check the closing comment I have mentioned another issue... If you can solve the issue it will be great.